### ISSUE TITLE
Cocos Creator | xzww 的源码能提供么？

### ISSUE THREAD

**Issue by gaoconggit** [zxcvb2850/comPorject#1]
Cocos Creator | xzww 的源码能提供么？

**Comment by zxcvb2850** [comment]
> Cocos Creator | xzww的源码能提供么？

不好意思那部分的代码不是写的，并不能提供 :see_no_evil:

**Comment by gaoconggit** [comment]
好的。

**Comment by gaoconggit** [comment]
是用Cocos Creator开发的，是吧

**Comment by zxcvb2850** [comment]
> 是用Cocos Creator开发的，是吧

对的

**Comment by gaoconggit** [comment]
大牛，源码可以提供一份么？

**Comment by zxcvb2850** [comment]
不不不，我是小菜鸡
github上的就是源码，服务器的代码我可给不了

**Comment by gaoconggit** [comment]
好吧。
你web-mobile目录中的代码是编译后生成的代码。
没办法在cocos creator编辑器中修改。

**Comment by zxcvb2850** [comment]
> 好吧。
> 你web-mobile目录中的代码是编译后生成的代码。
> 没办法在cocos creator编辑器中修改。

嗯嗯，是的，Cocos Creator我并不会，是同事写的，嵌入的

**Comment by gaoconggit** [comment]
还是谢谢了，通过您提供的源码还是学习到了很多。
